import { Lang } from "./i18n";

const TOPICS_FR = [
  "chnahiya ahsen haja 3taha lik rebi mn ghir walidik o khtek o oreo ?",
  "chnahiya 5 nasihat li kenti tebghi te3ti l rasek 9bel b 5ans",
  "is it better to speak or to die ?",
  "3lach imane ahsen binome fl 3alam ?",
  "chno houwa l holm dialk ?",
  "wach nta mansa ou wach howa chi haja bghiti tansa ?",
  "ila 3andak ghi yom wa7ed bach dir chi haja, chno ghadi tdir ?",
  "chno houwa l film li 3jbak bzaf u 3lach ?",
  "wach kayen chi haja katkhaf minha o 3lach ?",
  "ila kan 3andak superpower chno ghadi tkoun ?",
  "chno houwa l cours li kber fiha f hayatek ?",
  "ila kan momkin t3ich f ay waqt f tarikh chno ghadi tkhtaar ?",
  "chno houwa l kitab li 9ra u ghir tnsa ?",
  "wach houwa l shay li bghiti tbdlo f rasek ?",
  "chno kayn li ka y3tik motivation bach tstamer ?",
  "ila kan 3andak chance t7ki m3a chi chakhsiya tarikhiya, shkoun ?",
  "chno houwa l 7lam li bghiti y7sol f 5 snin ?",
  "wach houwa l shay li katfkr fih bzaf ?",
  "chno houwa l shay li katmna li kl nas y3arfoh ?",
  "ila kan momkin tsafar l ay blad chno ghadi tkhtaar ?",
  "chno houwa l shay li 3tah lik chwiya dyal courage ?",
  "wach houwa l 7adath li ghir tnsa f 7ayatek ?",
  "chno houwa l shay li bghiti t3lmo bach t7sen 7ayatek ?",
  "ila kan 3andak risala l rasek mn 10 snin, chno ghadi tgol ?",
];

const TOPICS_EN = [
  "What is the best thing that ever happened to you?",
  "If you could change one thing about yourself, what would it be?",
  "What is your biggest dream in life?",
  "Describe a moment that changed your life forever.",
  "What is the most important lesson you have learned so far?",
  "If you had only one day left, how would you spend it?",
  "What is a skill you wish you had learned earlier?",
  "Who is the person who influenced you the most and why?",
  "What does success mean to you?",
  "If you could travel anywhere in the world, where would you go?",
  "What is something you are afraid of and why?",
  "Describe your perfect day from morning to night.",
  "What is a book or movie that changed your perspective?",
  "What advice would you give to your younger self?",
  "If you could have any superpower, what would it be and why?",
  "What is something most people do not know about you?",
  "What motivates you to keep going when things get hard?",
  "If you could meet any historical figure, who would it be?",
  "What is the kindest thing someone has ever done for you?",
  "What does friendship mean to you?",
  "If you could live in any time period, which would you choose?",
  "What is something you are proud of that no one knows about?",
  "How do you deal with failure?",
  "What is your definition of happiness?",
];

const TOPICS_ES = [
  "Cual es la mejor cosa que te ha pasado en la vida?",
  "Si pudieras cambiar algo de ti mismo, que seria?",
  "Cual es tu mayor sueno en la vida?",
  "Describe un momento que cambio tu vida para siempre.",
  "Cual es la leccion mas importante que has aprendido?",
  "Si solo te quedara un dia, como lo pasarias?",
  "Cual es una habilidad que desearas haber aprendido antes?",
  "Quien es la persona que mas te ha influido y por que?",
  "Que significa el exito para ti?",
  "Si pudieras viajar a cualquier lugar del mundo, a donde irias?",
  "A que le tienes miedo y por que?",
  "Describe tu dia perfecto de la manana a la noche.",
  "Cual es un libro o pelicula que cambio tu perspectiva?",
  "Que consejo le darias a tu yo mas joven?",
  "Si pudieras tener cualquier superpoder, cual seria?",
  "Que es algo que la mayoria de la gente no sabe de ti?",
  "Que te motiva a seguir cuando las cosas se ponen dificiles?",
  "Si pudieras conocer a algun personaje historico, quien seria?",
  "Cual es la cosa mas amable que alguien ha hecho por ti?",
  "Que significa la amistad para ti?",
  "Si pudieras vivir en cualquier epoca, cual elegiras?",
  "De que estas orgulloso que nadie sabe?",
  "Como manejas el fracaso?",
  "Cual es tu definicion de felicidad?",
];

export function getRandomTopic(lang: Lang): string {
  const topics = lang === "en" ? TOPICS_EN : lang === "es" ? TOPICS_ES : TOPICS_FR;
  return topics[Math.floor(Math.random() * topics.length)];
}