import { Lang } from "./i18n";

const TOPICS_FR = [
  "La plus belle chose que Dieu t a donnee dans la vie a part ta famille et OREO ?",
  "Quels sont les 5 conseils que tu aurais voulu te donner il y a 5 ans ?",
  "Est-il mieux de parler ou de mourir ?",
  "Pourquoi Imane est la meilleure binome du monde ?",
  "Quel est ton reve dans la vie ?",
  "Qu est-ce que tu as oublie OU qu est-ce que tu voudrais oublier ?",
  "Si tu n avais qu une seule journee pour faire quelque chose, que ferais-tu ?",
  "Quel est le film qui t a le plus marque et pourquoi ?",
  "Y a-t-il quelque chose dont tu as peur et pourquoi ?",
  "Si tu avais un super pouvoir, lequel choisirais-tu ?",
  "Quelle est la lecon la plus importante que tu as apprise dans ta vie ?",
  "Qu est-ce que tu voudrais changer en toi ?",
  "Qu est-ce qui te donne la motivation de continuer ?",
  "Si tu avais la chance de parler avec un personnage historique, qui serait-il ?",
  "Quel est le reve que tu voudrais realiser dans 5 ans ?",
  "A quoi penses-tu le plus souvent ?",
  "Qu est-ce que tu voudrais que tout le monde sache ?",
  "Si tu pouvais voyager dans n importe quel pays, lequel choisirais-tu ?",
  "Qu est-ce qui t a donne un peu de courage dans ta vie ?",
  "Quel est l evenement que tu n oublieras jamais dans ta vie ?",
  "Qu est-ce que tu voudrais apprendre pour ameliorer ta vie ?",
  "Si tu avais un message a ecrire a toi-meme il y a 10 ans, que dirais-tu ?",
  "Qu est-ce qui te rend unique ?",
  "qu est ce que tu ressens en ce moment ?",
  "c est quoi la chose que t as toujours voulu dire a ta mere ?",
  "C'est quoi la premiere lecon que va aprendre a ton enfant dans le futur ?",
  "Qu est ce que tu aime chez toi ?",
  "La chose que tu voudrais changer on toi ",
  "Qu est ce que tu as appris de plus important dans ta vie ?",
  "La chose que tu vas changer dans le monde , si tu avais le pouvoir de la faire ?",
  

];

const TOPICS_EN = [
  "What is the best thing that ever happened to you?",
  "If you could change one thing about yourself, what would it be?",
  "What is your biggest dream in life?",
  "Describe a moment that changed your life forever.",
  "What is the most important lesson you have learned so far?",
  "If you had only one day left, how would you spend it?",
  "What is a skill you wish you had learned earlier?",
  "Who is the person who influenced you the most and why?",
  "What does success mean to you?",
  "If you could travel anywhere in the world, where would you go?",
  "What is something you are afraid of and why?",
  "Describe your perfect day from morning to night.",
  "What is a book or movie that changed your perspective?",
  "What advice would you give to your younger self?",
  "If you could have any superpower, what would it be and why?",
  "What is something most people do not know about you?",
  "What motivates you to keep going when things get hard?",
  "If you could meet any historical figure, who would it be?",
  "What is the kindest thing someone has ever done for you?",
  "What does friendship mean to you?",
  "If you could live in any time period, which would you choose?",
  "What is something you are proud of that no one knows about?",
  "How do you deal with failure?",
  "What is your definition of happiness?",
];

const TOPICS_ES = [
  "Cual es la mejor cosa que te ha pasado en la vida?",
  "Si pudieras cambiar algo de ti mismo, que seria?",
  "Cual es tu mayor sueno en la vida?",
  "Describe un momento que cambio tu vida para siempre.",
  "Cual es la leccion mas importante que has aprendido?",
  "Si solo te quedara un dia, como lo pasarias?",
  "Cual es una habilidad que desearas haber aprendido antes?",
  "Quien es la persona que mas te ha influido y por que?",
  "Que significa el exito para ti?",
  "Si pudieras viajar a cualquier lugar del mundo, a donde irias?",
  "A que le tienes miedo y por que?",
  "Describe tu dia perfecto de la manana a la noche.",
  "Cual es un libro o pelicula que cambio tu perspectiva?",
  "Que consejo le darias a tu yo mas joven?",
  "Si pudieras tener cualquier superpoder, cual seria?",
  "Que es algo que la mayoria de la gente no sabe de ti?",
  "Que te motiva a seguir cuando las cosas se ponen dificiles?",
  "Si pudieras conocer a algun personaje historico, quien seria?",
  "Cual es la cosa mas amable que alguien ha hecho por ti?",
  "Que significa la amistad para ti?",
  "Si pudieras vivir en cualquier epoca, cual elegiras?",
  "De que estas orgulloso que nadie sabe?",
  "Como manejas el fracaso?",
  "Cual es tu definicion de felicidad?",
];

export function getRandomTopic(lang: Lang): string {
  const topics = lang === "en" ? TOPICS_EN : lang === "es" ? TOPICS_ES : TOPICS_FR;
  return topics[Math.floor(Math.random() * topics.length)];
}