import { Lang } from "./i18n";

const TOPICS_FR = [
  "La plus belle chose que Dieu t a donnee dans la vie a part ta famille ?",
  "Quels sont les 5 conseils que tu aurais voulu te donner il y a 5 ans ?",
  "Est-il mieux de parler ou de mourir ?",
  "Quel est ton reve dans la vie ?",
  "Qu est-ce que tu as oublie OU qu est-ce que tu voudrais oublier ?",
  "Si tu n avais qu une seule journee pour faire quelque chose, que ferais-tu ?",
  "Quel est le film qui t a le plus marque et pourquoi ?",
  "Y a-t-il quelque chose dont tu as peur et pourquoi ?",
  "Si tu avais un super pouvoir, lequel choisirais-tu ?",
  "Quelle est la lecon la plus importante que tu as apprise dans ta vie ?",
  "Qu est-ce que tu voudrais changer en toi ?",
  "Qu est-ce qui te donne la motivation de continuer ?",
  "Si tu avais la chance de parler avec un personnage historique, qui serait-il ?",
  "Quel est le reve que tu voudrais realiser dans 5 ans ?",
  "A quoi penses-tu le plus souvent ?",
  "C'est quoi la chose que tu fais semblant de ne pas savoir sur toi-même ?",
  "C'est quoi la version de toi que tu caches aux autres ?",
  "Si tu savais que personne ne te jugerait, qu'est-ce que tu ferais différemment demain ?",
  "Est-ce que tu crois que tu mérites ce que tu as ? Sois honnête.",
  "C'est quoi le sacrifice que tu as fait et que personne n'a remarqué ?",
  "Si tu te réveilles demain millionnaire, c'est quoi ton premier move — et qu'est-ce que tu fais avec le reste ?",
  "Si tu pouvais entendre une seule personne te dire 'je suis fier de toi', ce serait qui — et pourquoi cette personne-là ?",
  "C'est quoi la toute première chose pour laquelle tu vas éduquer ton enfant dans le futur ?",
  "Si tu mourais demain, c'est quoi le truc que tu n'aurais pas eu le temps de dire ?",
  "C'est quoi l'injustice que tu vois chaque jour mais contre laquelle tu ne fais rien ?",
  "C'est quoi la dernière fois où tu as été vraiment heureux — et pourquoi ça ne dure pas ?",
  "Est-ce que tu es fier de ce que tu es devenu aujourd'hui ? Sois honnête.",
  "Est-ce que l'argent fait le bonheur ?",
  "Est-ce que l'argent signifie la liberté ?",
  "Est-ce qu'il faut toujours être honnête à 100% dans toutes les situations, ou l'honnêteté a ses limites ?",
  "Est-ce que le regard et le point de vue des gens comptent vraiment pour toi, ou tu fais juste semblant de t'en ficher ?",
  "Est-ce que les gagnants prennent vraiment tout  ?",
  "Qu est-ce que tu voudrais que tout le monde sache ?",
  "Si tu pouvais voyager dans n importe quel pays, lequel choisirais-tu ?",
  "Qu est-ce qui t a donne un peu de courage dans ta vie ?",
  "Quel est l evenement que tu n oublieras jamais dans ta vie ?",
  "Qu est-ce que tu voudrais apprendre pour ameliorer ta vie ?",
  "Si tu avais un message a ecrire a toi-meme il y a 10 ans, que dirais-tu ?",
  "Qu est-ce qui te rend unique ?",
  "qu est ce que tu ressens en ce moment ?",
  "c est quoi la chose que t as toujours voulu dire a ta mere ?",
  "C'est quoi la premiere lecon que va aprendre a ton enfant dans le futur ?",
  "Qu est ce que tu aime chez toi ?",
  "La chose que tu voudrais changer on toi ",
  "Qu est ce que tu as appris de plus important dans ta vie ?",
  "La chose que tu vas changer dans le monde , si tu avais le pouvoir de la faire ?",
  

];

const TOPICS_EN = [
  "What is the most beautiful thing God has given you in life, apart from your family?",
  "What are the 5 pieces of advice you wish you could have given yourself 5 years ago?",
  "Is it better to speak up or to die in silence?",
  "What is your dream in life?",
  "What have you forgotten — or what would you like to forget?",
  "If you only had one day to do something, what would you do?",
  "What is the movie that marked you the most and why?",
  "Is there something you are afraid of and why?",
  "If you had a superpower, which one would you choose?",
  "What is the most important lesson you have learned in your life?",
  "What would you like to change about yourself?",
  "What gives you the motivation to keep going?",
  "If you had the chance to talk to a historical figure, who would it be?",
  "What is the dream you want to achieve in 5 years?",
  "What do you think about the most?",
  "What is the thing you pretend not to know about yourself?",
  "What is the version of yourself that you hide from others?",
  "If you knew no one would judge you, what would you do differently tomorrow?",
  "Do you truly believe you deserve what you have? Be honest.",
  "What is the sacrifice you made that nobody noticed?",
  "If you woke up tomorrow as a millionaire, what is your first move — and what do you do with the rest?",
  "If you could hear one person say 'I am proud of you', who would it be — and why that person?",
  "What is the very first thing you will teach your future child?",
  "If you died tomorrow, what is the thing you would not have had time to say?",
  "What is the injustice you see every day but do nothing about?",
  "When was the last time you were truly happy — and why doesn't it last?",
  "Are you proud of who you have become today? Be honest.",
  "Does money really make you happy?",
  "Does money mean freedom?",
  "Should you always be 100% honest in every situation, or does honesty have its limits?",
  "Do people's opinions and judgments really matter to you, or are you just pretending not to care?",
  "Do winners really take it all?",
  "What is the thing you wish everyone knew?",
  "If you could travel to any country, which one would you choose?",
  "What gave you a little courage in your life?",
  "What is the event you will never forget in your life?",
  "What would you like to learn to improve your life?",
  "If you had a message to write to yourself 10 years ago, what would you say?",
  "What makes you unique?",
  "What are you feeling right now?",
  "What is the thing you have always wanted to say to your mother?",
  "What is the first lesson you will teach your future child?",
  "What do you love about yourself?",
  "What is the thing you would like to change about yourself?",
  "What is the most important thing you have learned in your life?",
  "What would you change in the world if you had the power to do it?",
];

const TOPICS_ES = [
  "¿Cuál es la cosa más hermosa que Dios te ha dado en la vida, aparte de tu familia?",
  "¿Cuáles son los 5 consejos que desearías haberte dado hace 5 años?",
  "¿Es mejor hablar o morir en silencio?",
  "¿Cuál es tu sueño en la vida?",
  "¿Qué has olvidado — o qué quisieras olvidar?",
  "Si solo tuvieras un día para hacer algo, ¿qué harías?",
  "¿Cuál es la película que más te ha marcado y por qué?",
  "¿Hay algo que te dé miedo y por qué?",
  "Si tuvieras un superpoder, ¿cuál elegirías?",
  "¿Cuál es la lección más importante que has aprendido en tu vida?",
  "¿Qué te gustaría cambiar de ti mismo?",
  "¿Qué te da la motivación para seguir adelante?",
  "Si tuvieras la oportunidad de hablar con un personaje histórico, ¿quién sería?",
  "¿Cuál es el sueño que quieres realizar en 5 años?",
  "¿En qué piensas más a menudo?",
  "¿Cuál es la cosa que finges no saber sobre ti mismo?",
  "¿Cuál es la versión de ti que escondes a los demás?",
  "Si supieras que nadie te juzgaría, ¿qué harías diferente mañana?",
  "¿Crees de verdad que mereces lo que tienes? Sé honesto.",
  "¿Cuál es el sacrificio que hiciste y que nadie notó?",
  "Si te despertaras mañana siendo millonario, ¿cuál sería tu primer movimiento — y qué harías con el resto?",
  "Si pudieras escuchar a una sola persona decirte 'estoy orgulloso de ti', ¿quién sería — y por qué esa persona?",
  "¿Cuál es la primera cosa que le enseñarás a tu futuro hijo?",
  "Si murieras mañana, ¿qué es lo que no habrías tenido tiempo de decir?",
  "¿Cuál es la injusticia que ves cada día pero contra la que no haces nada?",
  "¿Cuándo fue la última vez que fuiste verdaderamente feliz — y por qué no dura?",
  "¿Estás orgulloso de quien te has convertido hoy? Sé honesto.",
  "¿El dinero realmente hace la felicidad?",
  "¿El dinero significa libertad?",
  "¿Hay que ser siempre 100% honesto en todas las situaciones, o la honestidad tiene sus límites?",
  "¿La opinión y el juicio de la gente realmente importan para ti, o solo finges no importarte?",
  "¿Los ganadores realmente se lo llevan todo?",
  "¿Qué es lo que desearías que todo el mundo supiera?",
  "Si pudieras viajar a cualquier país, ¿cuál elegirías?",
  "¿Qué te dio un poco de valentía en tu vida?",
  "¿Cuál es el evento que nunca olvidarás en tu vida?",
  "¿Qué te gustaría aprender para mejorar tu vida?",
  "Si tuvieras un mensaje para escribirte a ti mismo hace 10 años, ¿qué dirías?",
  "¿Qué te hace único?",
  "¿Qué sientes en este momento?",
  "¿Cuál es la cosa que siempre quisiste decirle a tu madre?",
  "¿Cuál es la primera lección que le enseñarás a tu futuro hijo?",
  "¿Qué es lo que amas de ti mismo?",
  "¿Qué es lo que te gustaría cambiar de ti mismo?",
  "¿Cuál es la cosa más importante que has aprendido en tu vida?",
  "¿Qué cambiarías en el mundo si tuvieras el poder de hacerlo?",
];

const TOPICS_AR = [
  "ما هي أجمل شيء أعطاك الله إياه في الحياة، بعيداً عن عائلتك؟",
  "ما هي الـ5 نصائح التي كنت تتمنى أن تعطيها لنفسك قبل 5 سنوات؟",
  "هل من الأفضل أن تتكلم أم أن تموت في صمت؟",
  "ما هو حلمك في الحياة؟",
  "ما الذي نسيته — أو ما الذي تتمنى نسيانه؟",
  "لو كان عندك يوم واحد فقط تفعل فيه شيئاً، ماذا ستفعل؟",
  "ما هو الفيلم الذي أثّر فيك أكثر من غيره ولماذا؟",
  "هل هناك شيء تخاف منه ولماذا؟",
  "لو كان عندك قوة خارقة، أيها ستختار؟",
  "ما هو أهم درس تعلمته في حياتك؟",
  "ما الذي تريد تغييره في نفسك؟",
  "ما الذي يعطيك الدافع للاستمرار؟",
  "لو أتيحت لك الفرصة للحديث مع شخصية تاريخية، من سيكون؟",
  "ما هو الحلم الذي تريد تحقيقه خلال 5 سنوات؟",
  "ما الذي تفكر فيه أكثر من غيره؟",
  "ما هو الشيء الذي تتظاهر بأنك لا تعرفه عن نفسك؟",
  "ما هي النسخة منك التي تخفيها عن الآخرين؟",
  "لو كنت تعلم أن أحداً لن يحكم عليك، ماذا ستفعل بشكل مختلف غداً؟",
  "هل تؤمن حقاً أنك تستحق ما تملكه؟ كن صادقاً.",
  "ما هو التضحية التي قدمتها ولم يلاحظها أحد؟",
  "لو استيقظت غداً وأنت مليونير، ما هي أول خطوة ستتخذها — وماذا ستفعل بالباقي؟",
  "لو كان بإمكانك سماع شخص واحد يقول لك 'أنا فخور بك'، من سيكون — ولماذا هذا الشخص بالذات؟",
  "ما هو أول شيء ستعلمه لطفلك في المستقبل؟",
  "لو مت غداً، ما هو الشيء الذي لم يكن لديك وقت لقوله؟",
  "ما هو الظلم الذي تراه كل يوم لكنك لا تفعل شيئاً حياله؟",
  "متى كانت آخر مرة كنت فيها سعيداً حقاً — ولماذا لا يدوم ذلك؟",
  "هل أنت فخور بمن أصبحت اليوم؟ كن صادقاً.",
  "هل المال يصنع السعادة حقاً؟",
  "هل المال يعني الحرية؟",
  "هل يجب أن تكون صادقاً بنسبة 100% في كل المواقف، أم أن للصدق حدوده؟",
  "هل رأي الناس وحكمهم عليك يهمك حقاً، أم أنك تتظاهر فقط بأنه لا يهمك؟",
  "هل الفائزون يأخذون كل شيء فعلاً؟",
  "ما هو الشيء الذي تتمنى أن يعرفه الجميع؟",
  "لو كان بإمكانك السفر إلى أي بلد، أيها ستختار؟",
  "ما الذي أعطاك القليل من الشجاعة في حياتك؟",
  "ما هو الحدث الذي لن تنساه أبداً في حياتك؟",
  "ما الذي تريد تعلمه لتحسين حياتك؟",
  "لو كان عندك رسالة تكتبها لنفسك قبل 10 سنوات، ماذا ستقول؟",
  "ما الذي يجعلك مميزاً عن غيرك؟",
  "ما الذي تشعر به في هذه اللحظة؟",
  "ما هو الشيء الذي أردت دائماً قوله لأمك؟",
  "ما هو أول درس ستعلمه لطفلك في المستقبل؟",
  "ما الذي تحبه في نفسك؟",
  "ما هو الشيء الذي تريد تغييره في نفسك؟",
  "ما هو أهم شيء تعلمته في حياتك؟",
  "ما الذي ستغيره في العالم لو كان لديك القدرة على ذلك؟",
];

export function getRandomTopic(lang: Lang): string {
  const topics = lang === "en" ? TOPICS_EN : lang === "es" ? TOPICS_ES : TOPICS_FR;
  return topics[Math.floor(Math.random() * topics.length)];
}